### ISSUE TITLE
Refined Storage broke

### ISSUE THREAD

**Issue by Fastdragon1107** [P3rf3ctXZer0/Pixelmon-Evolved#1]
I tried using the crafter, and I set the thing to craft 1,000 inferium essence than while it was crafting, the grid and disks glitched out and everything in the disk went invisble. They were still in the disk but when I tried to view or grab them, they were not there.

**Comment by Fastdragon1107** [comment]
It was a visual glitch. I just had to restart my game.

**Comment by P3rf3ctXZer0** [comment]
Hm can I have your log files? I am having Ivo testing it.

**Comment by P3rf3ctXZer0** [comment]
Its not see tutorial for details
https://youtu.be/DihKGPOXgAs
